<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { agentGateway, type CalendarEvent } from '@/api'
import PageState from '@/components/PageState.vue'
import PageTitle from '@/components/PageTitle.vue'
import UiButton from '@/components/UiButton.vue'
import { localDateKey, time } from '@/utils/format'
const today = new Date(); const cursor = ref(new Date(today.getFullYear(), today.getMonth(), 1)); const events = ref<CalendarEvent[]>([]); const error = ref(''); const loading = ref(true)
const label = computed(() => new Intl.DateTimeFormat('ja-JP', { year: 'numeric', month: 'long' }).format(cursor.value))
const days = computed(() => { const first = new Date(cursor.value); const offset = first.getDay(); const start = new Date(first); start.setDate(1 - offset); return Array.from({ length: 42 }, (_, i) => { const day = new Date(start); day.setDate(start.getDate() + i); return day }) })
// ローカル日付（`localDateKey`）で比較する。UTC の `toISOString()` ベースで比較すると、
// JST の 09:00〜23:59 の予定が翌日の枠に表示されてしまう（issue #43）。
function key(day: Date) { return localDateKey(day) } function items(day: Date) { return events.value.filter(event => localDateKey(new Date(event.startsAt)) === key(day)) }
async function load() { loading.value = true; try { const from = key(days.value[0]); const to = key(days.value[41]); events.value = await agentGateway.listCalendarEvents(from, to) } catch { error.value = 'カレンダーを取得できません。' } finally { loading.value = false } }
// モバイルの一覧は表示中の月だけを日付ごとにまとめる。`calendar` は生の Google カレンダー ID
// （`…@group.calendar.google.com`）が入り得るので、表示には人間可読の `calendarName` を使う。
const agenda = computed(() => { const groups = new Map<string, { day: Date; events: CalendarEvent[] }>(); for (const event of [...events.value].sort((a, b) => a.startsAt.localeCompare(b.startsAt))) { const day = new Date(event.startsAt); if (day.getFullYear() !== cursor.value.getFullYear() || day.getMonth() !== cursor.value.getMonth()) continue; const dayKey = key(day); const group = groups.get(dayKey) ?? { day, events: [] }; group.events.push(event); groups.set(dayKey, group) } return [...groups.values()] })
const weekday = (day: Date) => new Intl.DateTimeFormat('ja-JP', { weekday: 'short' }).format(day)
const calendarLabel = (event: CalendarEvent) => event.calendarName || (event.calendar.includes('@') ? '' : event.calendar)
function move(amount: number) { cursor.value = new Date(cursor.value.getFullYear(), cursor.value.getMonth() + amount, 1); load() }
onMounted(load)
</script>
<template><section><PageTitle title="カレンダー" description="Google カレンダーとエージェントの予定"><template #actions><UiButton variant="secondary" to="/settings">連携設定</UiButton></template></PageTitle><div class="calendar-controls"><UiButton variant="secondary" @click="move(-1)">前月</UiButton><strong>{{ label }}</strong><UiButton variant="secondary" @click="move(1)">次月</UiButton></div><PageState :loading="loading" :error="error"/><div v-if="!loading" class="calendar"><div v-for="week in ['日','月','火','水','木','金','土']" :key="week" class="weekday">{{ week }}</div><div v-for="day in days" :key="key(day)" class="day" :class="{outside: day.getMonth() !== cursor.getMonth(), today: key(day) === key(today)}"><span class="date-num">{{ day.getDate() }}</span><div v-for="event in items(day)" :key="event.id" class="event" :style="{borderLeftColor:event.color}"><span>{{ time(event.startsAt) }}</span>{{ event.title }}</div></div></div><section v-if="!loading" class="agenda"><h3 class="section-title">{{ label }}の予定</h3><p v-if="!agenda.length" class="agenda-empty">予定はありません</p><div v-for="group in agenda" :key="key(group.day)" class="agenda-day" :class="{today: key(group.day) === key(today), past: key(group.day) < key(today)}"><div class="agenda-date"><strong>{{ group.day.getDate() }}</strong><span>{{ weekday(group.day) }}</span></div><ul><li v-for="event in group.events" :key="event.id" class="agenda-item" :style="{borderLeftColor:event.color}"><time>{{ time(event.startsAt) }}</time><div><strong>{{ event.title }}</strong><small v-if="calendarLabel(event)">{{ calendarLabel(event) }}</small></div></li></ul></div></section></section></template>
<style scoped>.calendar-controls{display:flex;align-items:center;justify-content:center;gap:20px;margin-bottom:14px}.calendar{display:grid;grid-template-columns:repeat(7,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line);background:#fff}.weekday{font-size:12px;color:#667085;padding:8px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);text-align:center}.day{height:110px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:5px;overflow:hidden}.date-num{font-size:12px}.outside{background:#f5f7fb;color:#98a2b3}.today .date-num{background:var(--primary);color:#fff;padding:1px 5px;border-radius:2px}.event{font-size:11px;margin-top:4px;padding:2px 3px;border-left:3px solid;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background:#f2f5fb}.event span{color:#667085;margin-right:3px}.agenda{display:none}@media(max-width:640px){.calendar{display:none}.agenda{display:block}.agenda-empty{color:var(--text-medium);font-size:13px;padding:16px 0}.agenda-day{display:flex;gap:12px;padding:12px 0;border-top:1px solid var(--line)}.agenda-day.past{opacity:.55}.agenda-date{width:36px;flex:none;display:grid;justify-items:center;align-content:start;line-height:1.2}.agenda-date strong{font-size:20px}.agenda-date span{font-size:11px;color:var(--text-medium)}.agenda-day.today .agenda-date strong{color:var(--primary)}.agenda-day ul{flex:1;min-width:0;list-style:none;margin:0;padding:0;display:grid;gap:8px}.agenda-item{display:flex;gap:10px;align-items:baseline;min-width:0;padding:8px 10px;background:var(--surface-1);border:1px solid var(--line);border-left:3px solid;border-radius:4px}.agenda-item time{flex:none;font-size:12px;color:var(--text-medium);font-variant-numeric:tabular-nums}.agenda-item div{min-width:0;display:grid;gap:2px}.agenda-item strong{font-size:14px;overflow-wrap:anywhere}.agenda-item small{font-size:11px;color:var(--text-medium);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}</style>
