<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { agentGateway, type CalendarEvent } from '@/api'
import PageState from '@/components/PageState.vue'
import PageTitle from '@/components/PageTitle.vue'
import UiButton from '@/components/UiButton.vue'
import { time } from '@/utils/format'
const today = new Date(); const cursor = ref(new Date(today.getFullYear(), today.getMonth(), 1)); const events = ref<CalendarEvent[]>([]); const error = ref(''); const loading = ref(true)
const label = computed(() => new Intl.DateTimeFormat('ja-JP', { year: 'numeric', month: 'long' }).format(cursor.value))
const days = computed(() => { const first = new Date(cursor.value); const offset = first.getDay(); const start = new Date(first); start.setDate(1 - offset); return Array.from({ length: 42 }, (_, i) => { const day = new Date(start); day.setDate(start.getDate() + i); return day }) })
function key(day: Date) { return day.toISOString().slice(0, 10) } function items(day: Date) { return events.value.filter(event => event.startsAt.slice(0, 10) === key(day)) }
async function load() { loading.value = true; try { const from = key(days.value[0]); const to = key(days.value[41]); events.value = await agentGateway.listCalendarEvents(from, to) } catch { error.value = 'カレンダーを取得できません。' } finally { loading.value = false } }
function move(amount: number) { cursor.value = new Date(cursor.value.getFullYear(), cursor.value.getMonth() + amount, 1); load() }
onMounted(load)
</script>
<template><section><PageTitle title="カレンダー" description="Google カレンダーとエージェントの予定"><template #actions><UiButton variant="secondary" to="/settings">連携設定</UiButton></template></PageTitle><div class="calendar-controls"><UiButton variant="secondary" @click="move(-1)">前月</UiButton><strong>{{ label }}</strong><UiButton variant="secondary" @click="move(1)">次月</UiButton></div><PageState :loading="loading" :error="error"/><div v-if="!loading" class="calendar"><div v-for="week in ['日','月','火','水','木','金','土']" :key="week" class="weekday">{{ week }}</div><div v-for="day in days" :key="key(day)" class="day" :class="{outside: day.getMonth() !== cursor.getMonth(), today: key(day) === key(today)}"><span class="date-num">{{ day.getDate() }}</span><div v-for="event in items(day)" :key="event.id" class="event" :style="{borderLeftColor:event.color}"><span>{{ time(event.startsAt) }}</span>{{ event.title }}</div></div></div><section class="agenda"><h3 class="section-title">今後の予定</h3><div v-for="event in events" :key="event.id" class="agenda-row"><span :style="{background:event.color}"></span><div><strong>{{ event.title }}</strong><p>{{ new Date(event.startsAt).toLocaleDateString('ja-JP') }} {{ time(event.startsAt) }} · {{ event.calendar }}</p></div></div></section></section></template>
<style scoped>.calendar-controls{display:flex;align-items:center;justify-content:center;gap:20px;margin-bottom:14px}.calendar{display:grid;grid-template-columns:repeat(7,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line);background:#fff}.weekday{font-size:12px;color:#667085;padding:8px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);text-align:center}.day{height:110px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:5px;overflow:hidden}.date-num{font-size:12px}.outside{background:#f5f7fb;color:#98a2b3}.today .date-num{background:var(--primary);color:#fff;padding:1px 5px;border-radius:2px}.event{font-size:11px;margin-top:4px;padding:2px 3px;border-left:3px solid;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background:#f2f5fb}.event span{color:#667085;margin-right:3px}.agenda{display:none}@media(max-width:640px){.calendar{display:none}.agenda{display:block;border-top:1px solid var(--line)}.agenda-row{display:flex;gap:10px;padding:13px 0;border-bottom:1px solid var(--line)}.agenda-row>span{width:3px;align-self:stretch}.agenda-row strong{font-size:14px}.agenda-row p{font-size:12px;color:#667085;margin:4px 0 0}}</style>
