<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { agentGateway, type FinanceSummary, type Transaction } from '@/api'
import PageState from '@/components/PageState.vue'
import { yen } from '@/utils/format'
import FormField from '@/components/FormField.vue'
import PageTitle from '@/components/PageTitle.vue'
import UiButton from '@/components/UiButton.vue'
const month = ref(new Date().toISOString().slice(0, 7)); const summary = ref<FinanceSummary>(); const transactions = ref<Transaction[]>([]); const loading = ref(true); const error = ref(''); const form = ref({ date: new Date().toISOString().slice(0, 10), category: '食費', description: '', amount: 0, kind: 'expense' as 'income' | 'expense' })
async function load() { loading.value = true; try { [summary.value, transactions.value] = await Promise.all([agentGateway.getFinanceSummary(month.value), agentGateway.listTransactions(month.value)]) } catch { error.value = '家計データを取得できません。' } finally { loading.value = false } }
async function add() { if (!form.value.description || form.value.amount <= 0) return; const entry = await agentGateway.createTransaction(form.value); transactions.value.unshift(entry); await load(); form.value.description = ''; form.value.amount = 0 }
onMounted(load)
</script>
<template><section><PageTitle title="家計" description="収支を記録し、月ごとの傾向を把握します"><template #actions><input v-model="month" type="month" @change="load" /></template></PageTitle><PageState :loading="loading" :error="error"/><template v-if="summary"><div class="summary"><div><span>収入</span><strong class="income">{{ yen(summary.income) }}</strong></div><div><span>支出</span><strong class="expense">{{ yen(summary.expense) }}</strong></div><div><span>差引</span><strong>{{ yen(summary.balance) }}</strong></div></div><form class="transaction-form surface" @submit.prevent="add"><h3>取引を追加</h3><FormField label="種別"><select v-model="form.kind"><option value="expense">支出</option><option value="income">収入</option></select></FormField><FormField label="日付"><input v-model="form.date" type="date" /></FormField><FormField label="カテゴリ"><input v-model="form.category" /></FormField><FormField label="内容"><input v-model="form.description" placeholder="例: 昼食" /></FormField><FormField label="金額"><input v-model.number="form.amount" type="number" min="1" /></FormField><UiButton type="submit">登録</UiButton></form><section><h3 class="section-title">直近の履歴</h3><div class="transactions"><div v-for="item in transactions" :key="item.id" class="transaction"><time>{{ item.date.slice(5).replace('-', '/') }}</time><div><strong>{{ item.description }}</strong><span>{{ item.category }}</span></div><b :class="item.kind">{{ item.kind === 'income' ? '+' : '-' }}{{ yen(item.amount) }}</b></div></div></section></template></section></template>
<style scoped>.month-picker{border:1px solid var(--field);padding:7px;border-radius:2px;min-height:40px}.summary{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line);margin-bottom:24px}.summary div{padding:14px;border-right:1px solid var(--line)}.summary div:last-child{border:0}.summary span{display:block;font-size:12px;color:#667085}.summary strong{font-size:20px}.income{color:var(--primary)}.expense{color:#b42318}.transaction-form{padding:16px;display:grid;grid-template-columns:repeat(5,1fr) auto;gap:10px;align-items:end;margin-bottom:28px}.transaction-form h3{grid-column:1/-1;margin:0;font-size:14px}.transactions{border-top:1px solid var(--line)}.transaction{display:flex;align-items:center;gap:14px;padding:13px 4px;border-bottom:1px solid var(--line)}.transaction time{font-size:12px;color:#667085;width:38px}.transaction div{display:grid;gap:3px}.transaction strong{font-size:14px}.transaction span{font-size:12px;color:#667085}.transaction b{margin-left:auto;font-size:14px}.transaction b.income{color:var(--primary)}.transaction b.expense{color:#b42318}@media(max-width:640px){.summary strong{font-size:16px}.transaction-form{grid-template-columns:1fr 1fr}.transaction-form h3{grid-column:1/-1}.transaction-form .form-field:nth-child(4),.transaction-form .form-field:nth-child(5),.transaction-form .ui-button{grid-column:span 2}}</style>
